### PR TITLE
Fix compile failure

### PR DESCRIPTION
**Pull request by xIsm4**

### CODE REVIEW

**Comment by 4drian3d** [comment]
From what I have seen, the problem does not come from Paper, but from Waterfall in the Common module.
```
[INFO] Reactor Summary for CommandWhitelist 2.1.1:
[INFO]
[INFO] CommandWhitelist ................................... SUCCESS [  2.977 s]
[INFO] CommandWhitelist ................................... FAILURE [ 53.476 s]
[INFO] CommandWhitelist ................................... SKIPPED
[INFO] CommandWhitelist ................................... SKIPPED
[INFO] CommandWhitelist ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57.282 s
[INFO] Finished at: 2021-09-13T14:13:37-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Common: Could not resolve dependencies for project eu.endermite.commandwhitelist:Common:jar:2.1.1: Could not find artifact io.github.waterfallmc:waterfall-api:jar:1.17-R0.1-SNAPSHOT in pluginwiki-repo (https://ci.pluginwiki.us/plugin/repository/everything/) -> [Help 1]
```

By adding the Paper repository in the Common module, it compiles correctly.

**Comment by YouHaveTrouble** [comment]
> From what I have seen, the problem come from Paper and Waterfall in the Common module.
> By adding the Paper repository in the Common module, it compiles correctly.

Could you test building the latest commit?

**Comment by xIsm4** [comment]
> > ve seen, the problem come from Paper and Waterfall in the Common module.
> > By adding the Paper repository in the Common module, it compiles correctly.
> 
> Could you test building the latest commit?

Actually i tested the old, and i couldn't compile the New i could.

**Comment by YouHaveTrouble** [comment]
I also remaned modules so it's easier to tell which build fails. Will close the PRs now since it's fixed. Thanks for pointing out the error.

**Pull request closed without merging**
