### PR TITLE
feat: add support to Folia

### PR DESCRIPTION
**Pull request by Aitooor**
Testet and working: https://imgur.com/a/ru6zQyW

### CODE REVIEW

**Comment by YouHaveTrouble** [comment]
Okay, a question first. At first glance I don't see any changes made in the folia module besides adding folia-supported tag in plugin.yml, is the module necessary at all or can folia-supported be just added to bukkit module? Maybe I'm missing something?

**Comment by Aitooor** [comment]
> Okay, a question first. At first glance I don't see any changes made in the folia module besides adding folia-supported tag in plugin.yml, is the module necessary at all or can folia-supported be just added to bukkit module? Maybe I'm missing something?

Changed Server#scheduler to Server#asyncScheduler

**Comment by YouHaveTrouble** [comment]
If that is the only change then I would consider just swapping the scheduler to a CompletableFuture for config reload. It's way smaller change and should work perfectly fine on both bukkit and folia

**Comment by Aitooor** [comment]
> If that is the only change then I would consider just swapping the scheduler to a CompletableFuture for config reload. It's way smaller change and should work perfectly fine on both bukkit and folia

Suree no problem, thanks for considering me

**Comment by Aitooor** [comment]
You can close this PR if you want then 😄

**Comment by YouHaveTrouble** [comment]
Do you want to change it to the CompletableFuture, or should I?

**Comment by YouHaveTrouble** [comment]
Pushed the change to completable future and folia compatible in plugin.yml. Thanks for figuring out what needed to be changed!

**Pull request closed without merging**
